<?php
/**
 * Created by PhpStorm.
 * User: isandre
 * Date: 08/10/18
 * Time: 21:32
 */
namespace Unite;

class Elf extends Unit{

    public function walk($walk)
    {
        return parent::walk($walk, 5); // TODO: Change the autogenerated stub
    }
}