<?php
/**
 * Created by PhpStorm.
 * User: isandre
 * Date: 08/10/18
 * Time: 21:33
 */
namespace Unite;

class Soldier extends Unit{

    public function walk($walk)
    {
        return parent::walk($walk, 2); // TODO: Change the autogenerated stub
    }

}